repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  # Published chart example
  - name: apache                            # name of this release
    namespace: default                      # target namespace
    labels:                                  # Arbitrary key value pairs for filtering releases
      app: apache
    chart: bitnami/apache
    version: 9.1.11
    values:
      # value files passed via --values
    - values.yaml
    # wait for k8s resources via --wait. Defaults to `false`
    wait: true
    # time in seconds to wait for any individual Kubernetes operation (like Jobs for hooks, and waits on pod/pvc/svc/deployment readiness) (default 300)
    timeout: 60
    # performs pods restart for the resource if applicable
    recreatePods: true
    # forces resource update through delete/recreate if needed
    force: true